"""用户问题识别、规范化与路由模块。"""

from rag.query.enhancement import (
    QUERY_ENHANCEMENT_SCHEMA,
    QUERY_ENHANCEMENT_SYSTEM_PROMPT,
    QueryEnhancement,
    QueryEnhancementProtocolError,
    build_query_enhancement_prompt,
    compile_retrieval_queries,
    parse_and_validate_query_enhancement,
)
from rag.query.router import (
    QueryDecision,
    QueryReason,
    QueryRoute,
    route_query,
)
from rag.query.query_assessment import (
    QUERY_ASSESSMENT_SYSTEM_PROMPT,
    QueryAssessment,
    QueryAssessmentProtocolError,
    assess_query,
    parse_and_validate_query_assessment,
)
from rag.query.answer_review import (
    ANSWER_REVIEW_SCHEMA,
    ANSWER_REVIEW_SYSTEM_PROMPT,
    AnswerReviewDecision,
    AnswerReviewProtocolError,
    build_answer_review_prompt,
    parse_and_validate_answer_review,
    review_answer,
)
from rag.core.contracts import (
    AnswerMode,
    BusinessRoute,
    RouteDecision,
)
from rag.query.agentic_retrieval import (
    AGENTIC_RETRIEVAL_SYSTEM_PROMPT,
    EVIDENCE_ASSISTANT_TOOLS,
    FINALIZE_EVIDENCE_TOOL,
    AgenticRetrievalError,
    EvidenceSearch,
    EvidenceSelection,
    MAX_SELECTED_EVIDENCE,
    MAX_SUPPLEMENTAL_SEARCHES,
    SEARCH_LAW_TOOL,
    build_agent_messages,
    run_agentic_retrieval,
    validate_supplemental_query,
)

__all__ = [
    "AnswerMode",
    "BusinessRoute",
    "QUERY_ENHANCEMENT_SCHEMA",
    "QUERY_ENHANCEMENT_SYSTEM_PROMPT",
    "QueryDecision",
    "QueryEnhancement",
    "QueryEnhancementProtocolError",
    "QueryReason",
    "QueryRoute",
    "RouteDecision",
    "build_query_enhancement_prompt",
    "compile_retrieval_queries",
    "parse_and_validate_query_enhancement",
    "route_query",
    "QUERY_ASSESSMENT_SYSTEM_PROMPT",
    "QueryAssessment",
    "QueryAssessmentProtocolError",
    "assess_query",
    "parse_and_validate_query_assessment",
    "AGENTIC_RETRIEVAL_SYSTEM_PROMPT",
    "EVIDENCE_ASSISTANT_TOOLS",
    "FINALIZE_EVIDENCE_TOOL",
    "AgenticRetrievalError",
    "EvidenceSearch",
    "EvidenceSelection",
    "MAX_SELECTED_EVIDENCE",
    "MAX_SUPPLEMENTAL_SEARCHES",
    "SEARCH_LAW_TOOL",
    "build_agent_messages",
    "run_agentic_retrieval",
    "validate_supplemental_query",
    "ANSWER_REVIEW_SCHEMA",
    "ANSWER_REVIEW_SYSTEM_PROMPT",
    "AnswerReviewDecision",
    "AnswerReviewProtocolError",
    "build_answer_review_prompt",
    "parse_and_validate_answer_review",
    "review_answer",
]
